### ISSUE TITLE
ROE generic thrusters have turbopump ignition spoolup

### ISSUE THREAD

**Issue by siimav** [KSP-RO/ROEngines#87] opened 2020-09-13 21:13 UTC
They take ~2s to start producing any thrust after hitting the throttle. The RO generic thrusters on the other hand ignite within 0.1-0.2 seconds.
After some digging I found out that the `minThrust` and `maxThrust` fields are what make the RO thruster behave the way it is.
```
MODULE
{
	name = ModuleEnginesRF
	minThrust = 0
	maxThrust = 2
}
```
Not sure if we want to add those fields to ROE as well or try to find a better solution.

**Comment by siimav** [comment] 2020-09-13 22:25
Looks like this issue is related to #78.
Further discussion can be found [here](https://discordapp.com/channels/319857228905447436/663102368887472156/754814828329042012).

**Comment by siimav** [comment] 2020-09-13 22:39
@Capkirk123 testing to see whether I can assign the task to you now

**Comment by Capkirk123** [comment] 2020-09-17 03:53
Cannot reproduce? All ROE generic thrusters have no measurable response time in my 1.8.1 install. If this is a 1.10 thing, there are better ways to cut down the response time.
`throttleResponseRate = 100`
Should make their startup instantaneous.

**Comment by siimav** [comment] 2020-09-17 09:46
@Capkirk123 Did you test with #78?

**Comment by DRVeyl** [comment] 2020-11-20 21:20
I went ahead and merged with #78.  If this remains a problem in 1.10 (appears not a problem in 1.8?) please let me know the actual affected parts and where `throttleResponseRate` should be set (ie where in the config?).

**Comment by StonesmileGit** [comment] 2020-12-03 13:07
The Dual Radial Engine appears to have an ignition spoolup of about 1 sec and the 0.4 kN and 0.44kN engines appears to have a two sec ingition spoolup in KSP 1.8.1

**Comment by lpgagnon** [comment] 2020-12-03 13:26
https://discord.com/channels/319857228905447436/663102368887472156/782445627384397846

**Comment by DRVeyl** [comment] 2021-03-13 21:57
This appears to have been fixed at some point leading up to the current ROE master, or by recent RealFuels work.

**Closed by DRVeyl** 2021-03-13 21:57 UTC
